In [1]:
#import necessary packages
import os
import argparse
import cv2
import numpy as np
import sys
import importlib.util

In [2]:
CWD_PATH = os.chdir('E:/ambience_mode')


In [3]:
CWD_PATH = os.getcwd()
print(CWD_PATH)

E:\ambience_mode


In [8]:
#required variables
MODEL_NAME = 'models/'
GRAPH_NAME = 'tflite_model_5_quant.tflite'
LABELMAP_NAME = 'labelmap.txt'
VIDEO_NAME = 'video_test/video_test_2.mp4'
min_conf_threshold = float(0.7)
use_TPU = None

# Import TensorFlow libraries
# If tflite_runtime is installed, import interpreter from tflite_runtime, else import from regular tensorflow
# If using Coral Edge TPU, import the load_delegate library
pkg = importlib.util.find_spec('tflite_runtime')
if pkg:
    from tflite_runtime.interpreter import Interpreter
    if use_TPU:
        from tflite_runtime.interpreter import load_delegate
else:
    from tensorflow.lite.python.interpreter import Interpreter
    if use_TPU:
        from tensorflow.lite.python.interpreter import load_delegate

# If using Edge TPU, assign filename for Edge TPU model
if use_TPU:
    # If user has specified the name of the .tflite file, use that name, otherwise use default 'edgetpu.tflite'
    if (GRAPH_NAME == 'detect.tflite'):
        GRAPH_NAME = 'edgetpu.tflite'   

# Get path to current working directory
CWD_PATH = os.getcwd()

# Path to video file
VIDEO_PATH = os.path.join(CWD_PATH,VIDEO_NAME)

# Path to .tflite file, which contains the model that is used for object detection
PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,GRAPH_NAME)

# Path to label map file
PATH_TO_LABELS = os.path.join(CWD_PATH,MODEL_NAME,LABELMAP_NAME)

# Load the label map
with open(PATH_TO_LABELS, 'r') as f:
    labels = [line.strip() for line in f.readlines()]

# Have to do a weird fix for label map if using the COCO "starter model" from
# https://www.tensorflow.org/lite/models/object_detection/overview
# First label is '???', which has to be removed.
if labels[0] == '???':
    del(labels[0])

# Load the Tensorflow Lite model.
# If using Edge TPU, use special load_delegate argument
if use_TPU:
    interpreter = Interpreter(model_path=PATH_TO_CKPT,
                              experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
    print(PATH_TO_CKPT)
else:
    interpreter = Interpreter(model_path=PATH_TO_CKPT)

interpreter.allocate_tensors()

In [9]:
# Get model details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
height = input_details[0]['shape'][1]
width = input_details[0]['shape'][2]
output_details[0]
scale,zero_point = output_details[0]['quantization']
print('Scale: '+str(scale)+' | Zero Point: '+str(zero_point))

Scale: 0.00390625 | Zero Point: 0


In [15]:
VIDEO_PATH
min_conf_threshold = 0.4

In [25]:
floating_model = (input_details[0]['dtype'] == np.float32)

input_mean = 127.5
input_std = 127.5

# Open video file
video = cv2.VideoCapture(VIDEO_PATH)
imW = video.get(cv2.CAP_PROP_FRAME_WIDTH)
imH = video.get(cv2.CAP_PROP_FRAME_HEIGHT)

# Loop over every image and perform detection
while (True):

    # Acquire frame and resize to expected shape [1xHxWx3]
    ret, frame = video.read()
    if not ret:
      print('Reached the end of the video!')
      break
    
    # Load frame and resize to expected shape [1xHxWx3]
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frame_resized = cv2.resize(frame_rgb, (width, height))
    input_data = np.expand_dims(frame_resized, axis=0)
    frameH, frameW = int(imH),int(imW) 

    # Normalize pixel values if using a floating model (i.e. if model is non-quantized)
    if floating_model:
        input_data = (np.float32(input_data) - input_mean) / input_std

    # Perform the actual detection by running the model with the image as input
    interpreter.set_tensor(input_details[0]['index'],input_data)
    interpreter.invoke()
    
    # Retrieve detection results
    #boxes = interpreter.get_tensor(output_details[0]['index'])[0] # Bounding box coordinates of detected objects
    #classes = interpreter.get_tensor(output_details[1]['index'])[0] # Class index of detected objects
    scores = interpreter.get_tensor(output_details[0]['index'])[0] # Confidence of detected objects
    #num = interpreter.get_tensor(output_details[3]['index'])[0]  # Total number of detected objects (inaccurate and not needed)
    scores = (scores-zero_point)*scale
    print(scores)
    
    label_index = np.argmax(scores, axis=0)
    #predicted_label.append(labels[label_index])
    print("***")
    # Loop over all detections and draw detection box if confidence is above minimum threshold
    for i in range(len(scores)):
        if ((scores[i] > min_conf_threshold) and (scores[i] <= 1.0)):
            print("******")
            # Get bounding box coordinates and draw box
            # Interpreter can return coordinates that are outside of image dimensions, need to force them to be within image using max() and min()
            ymin = 3
            xmin = 3
            ymax = frameH-3
            xmax = frameW-3
            
            cv2.rectangle(frame, (xmin,ymin), (xmax,ymax), (10, 255, 0), 2)

            # Draw label
            object_name = labels[label_index] # Look up object name from "labels" array using class index
            label = '%s: %d%%' % (object_name, int(scores[i]*100)) # Example: 'person: 72%'
            labelSize, baseLine = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2) # Get font size
            label_ymin = max(ymin, labelSize[1] + 10) # Make sure not to draw label too close to top of window
            cv2.rectangle(frame, (xmin, label_ymin-labelSize[1]-10), (xmin+labelSize[0], label_ymin+baseLine-10), (255, 255, 255), cv2.FILLED) # Draw white box to put label text in
            cv2.putText(frame, label, (xmin, label_ymin-7), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 0), 2) # Draw label text
    print("****")
    # All the results have been drawn on the frame, so it's time to display it.
    cv2.imshow('Object detector', frame)

    # Press any key to continue to next image, or press 'q' to quit
    if cv2.waitKey(1) == ord('q'):
        break

# Clean up
cv2.destroyAllWindows()

[0.11328125 0.03515625 0.1953125  0.65625   ]
***
******
****
[0.12109375 0.03125    0.1953125  0.65234375]
***
******
****
[0.12109375 0.03125    0.1953125  0.65234375]
***
******
****
[0.11328125 0.0390625  0.18359375 0.6640625 ]
***
******
****
[0.12109375 0.03125    0.2109375  0.63671875]
***
******
****
[0.15625    0.03515625 0.23046875 0.578125  ]
***
******
****
[0.0390625  0.046875   0.1953125  0.71484375]
***
******
****
[0.046875   0.05078125 0.19140625 0.70703125]
***
******
****
[0.0703125  0.046875   0.17578125 0.70703125]
***
******
****
[0.0859375  0.04296875 0.21484375 0.65625   ]
***
******
****
[0.15234375 0.06640625 0.26953125 0.51171875]
***
******
****
[0.140625   0.08203125 0.15625    0.62109375]
***
******
****
[0.08984375 0.0390625  0.0625     0.8125    ]
***
******
****
[0.10546875 0.03515625 0.1171875  0.7421875 ]
***
******
****
[0.1171875  0.04296875 0.10546875 0.73828125]
***
******
****
[0.16796875 0.046875   0.16796875 0.6171875 ]
***
******
****
[0.35546