In [2]:
import numpy as np

#question no 1
X = np.array([[4.0,2.0,0.60],[4.2,2.1,0.59],[3.9,2.0,0.58],[4.3,2.1,0.62],[4.1,2.2,0.63]])
Z = np.transpose(X)    
print(" Input Matrix")
print("--------------")
print(X)
print()
print(" Covariance Matrix")
print("-------------------")
covariance = np.cov(Z)
print(covariance)
print()

 Input Matrix
--------------
[[4.   2.   0.6 ]
 [4.2  2.1  0.59]
 [3.9  2.   0.58]
 [4.3  2.1  0.62]
 [4.1  2.2  0.63]]

 Covariance Matrix
-------------------
[[0.025   0.0075  0.00175]
 [0.0075  0.007   0.00135]
 [0.00175 0.00135 0.00043]]



In [5]:
#mahanlobis distance question no.2
p = np.array([4.3,1.9,0.70])
q = np.array([3.9,2.0,0.58])
sub = np.array([np.subtract(p,q)])
subT = np.transpose(sub)

inverse = np.linalg.inv(covariance) 
inverse = np.around(inverse, decimals=1, out=None)

prod1 = np.dot(sub,inverse)
result = np.dot(prod1,subT)

print("The Mahalanobis Distance Between", end = " ")
print("("+str(p[0])+','+str(p[1])+','+str(p[2])+")", end = " and ")
print("("+str(q[0])+','+str(q[1])+','+str(q[2])+")", end = " is: ")
print()

print(result)


The Mahalanobis Distance Between (4.3,1.9,0.7) and (3.9,2.0,0.58) is: 
[[119.83448]]


In [46]:
xCom = [[4.1,2.08,0.604],[4.1,2.08,0.604],[4.1,2.08,0.604],[4.1,2.08,0.604],[4.1,2.08,0.604]]

#print(zCom)
X = np.subtract(x,xCom)
print(X)
Xt = np.transpose(X)
print(Xt)
result = np.dot(X,Xt)
result = result/4
#print(result)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [8]:
A = np.array([[4,3],[2,1]])
B = np.array([4,3])

C = np.subtract(A,B)

print(A[0][1])


3


In [32]:
x = np.array([[4.0,2.0,0.60],[4.2,2.1,0.59],[3.9,2.0,0.58],[4.3,2.1,0.62],[4.1,2.2,0.63]])
xc = np.array([4.1,2.08,0.604])
row = 5
j = 3
k = 3
j-=1
k-=1
sum = 0
result = 0
for i in range(row):
    sum += (x[i][j]-xc[j])*(x[i][k]-xc[k])
    
result = round((sum/4),5)
print("COV("+str(j)+","+str(k)+") : "+str(result))


COV(2,2) : 0.00043


[14]
